FROM centos:centos8
RUN dnf install -y java-1.8.0-openjdk
RUN curl --create-dirs -o ~/.embulk/bin/embulk -L "https://dl.embulk.org/embulk-latest.jar" && \
    chmod +x ~/.embulk/bin/embulk && \
    echo 'export PATH="$HOME/.embulk/bin:$PATH"' >> ~/.bashrc && \
    source ~/.bashrc
RUN export PATH="$HOME/.embulk/bin:$PATH"; embulk gem install embulk-input-mysql; embulk gem install embulk-output-mysql